### ISSUE TITLE
Not enough stacking.

### ISSUE THREAD

**Issue by dxu** [ericslee/Grocks#2]

**Comment by dxu** [comment]
Expectation:
![](http://s1.ibtimes.com/sites/www.ibtimes.com/files/styles/v2_article_large/public/2013/08/21/worlds-tallest-lego-tower.jpg)

**Comment by judytrinh** [comment]
this is low priority

**Comment by ericslee** [comment]
no TROLLS ALLOWED

**Comment by dxu** [comment]
man i was such a hoot what happened to me
